"""Generates data/demo_full.csv - a single, comprehensive demo dataset
deliberately shaped to exercise every deterministic chart type
app/narrative/charts.py can produce, and to give the Predict page's own
forecast demo (app/routers/predict.py) a real trend to beat the naive
baseline with.

Seeded (numpy default_rng, fixed seed) - re-running this script reproduces
the exact same file byte-for-byte, so data/demo_full.csv is meant to be
regenerated by running this script again, never hand-edited.

Column -> exercised chart / finding:
  order_date + revenue   -> TREND finding -> LINE chart (clear upward
                             trend, weekly + Nov/Dec seasonal pattern)
  revenue vs cost        -> CORRELATION finding (~0.7, Pearson) -> SCATTER
                             chart
  satisfaction_score     -> a discrete 1-5 integer rating -> value-count
                             BAR chart (app/narrative/charts.py's Part 4 fix)
  shipping_days          -> a numeric column with no engineered trend or
                             correlation -> an ordinary HISTOGRAM
  category, region       -> low-cardinality categoricals (a bonus
                             categorical bar chart too, not load-bearing)
  order_id               -> a genuine per-row identifier - deliberately
                             excluded from modeling by leakage prevention

`revenue`, summed per month (app/modeling/task_selection.py aggregates a
numeric forecast target by SUM), is also what the Predict page's own
"forecast monthly revenue" demo question forecasts - the trend here is
strong and clean enough that a real Prophet/ARIMA fit clearly beats the
naive-last-value baseline (verified empirically below when this script
runs, and again in tests/test_demo_full_dataset.py against the real
exploration/narrative pipeline).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

SEED = 20260803
N_DAYS = 913  # ~30 months of days - comfortably clears the 24-aggregated-period forecast floor once resampled to monthly
START_DATE = "2023-01-01"
MEAN_ORDERS_PER_DAY = 5

CATEGORIES = ["widgets", "gadgets", "tools", "accessories"]
REGIONS = ["north", "south", "east", "west"]
TARGET_REVENUE_COST_CORRELATION = 0.7


def generate() -> pd.DataFrame:
    rng = np.random.default_rng(SEED)
    dates = pd.date_range(START_DATE, periods=N_DAYS, freq="D")

    order_dates: list[str] = []
    day_revenue_targets: list[float] = []
    for day_index, date in enumerate(dates):
        trend = 500 + 2.6 * day_index
        weekly = 25 * np.sin(2 * np.pi * day_index / 7)
        yearly_bump = 150.0 if date.month in (11, 12) else 0.0
        day_level = trend + weekly + yearly_bump
        n_orders = int(rng.poisson(MEAN_ORDERS_PER_DAY)) + 1  # at least one order/day
        for _ in range(n_orders):
            order_dates.append(date.strftime("%Y-%m-%d"))
            day_revenue_targets.append(day_level / n_orders)

    n = len(order_dates)
    day_revenue_targets = np.asarray(day_revenue_targets)
    per_order_noise = rng.normal(0, 14, n)
    revenue = np.clip(day_revenue_targets + per_order_noise, 5, None)

    # Cost correlated with revenue at TARGET_REVENUE_COST_CORRELATION by
    # construction (the standard "rho*z + sqrt(1-rho^2)*independent_z" trick
    # for a target Pearson correlation), then rescaled to a realistic range.
    rho = TARGET_REVENUE_COST_CORRELATION
    z_revenue = (revenue - revenue.mean()) / revenue.std()
    independent_noise = rng.normal(0, 1, n)
    z_cost = rho * z_revenue + np.sqrt(1 - rho**2) * independent_noise
    cost = np.clip(60 + z_cost * 25, 5, None)

    satisfaction_score = rng.integers(1, 6, n)  # discrete 1-5, deliberately unrelated to anything else
    shipping_days = rng.lognormal(mean=1.1, sigma=0.4, size=n)  # continuous, no engineered trend/correlation
    category = rng.choice(CATEGORIES, size=n)
    region = rng.choice(REGIONS, size=n)
    order_id = [f"ORD-{i:06d}" for i in range(n)]

    return pd.DataFrame(
        {
            "order_id": order_id,
            "order_date": order_dates,
            "revenue": np.round(revenue, 2),
            "cost": np.round(cost, 2),
            "satisfaction_score": satisfaction_score,
            "shipping_days": np.round(shipping_days, 2),
            "category": category,
            "region": region,
        }
    )


def main() -> None:
    df = generate()
    out_path = Path(__file__).resolve().parent.parent / "data" / "demo_full.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path, index=False)

    pearson_r = df["revenue"].corr(df["cost"])
    monthly = df.assign(order_date=pd.to_datetime(df["order_date"])).set_index("order_date").resample("MS")["revenue"].sum()
    print(f"wrote {len(df)} rows ({df['order_date'].nunique()} distinct days) to {out_path}")
    print(f"revenue/cost Pearson r = {pearson_r:.3f} (target {TARGET_REVENUE_COST_CORRELATION})")
    print(f"{len(monthly)} monthly-aggregated revenue periods, range [{monthly.min():.0f}, {monthly.max():.0f}]")
    print(f"satisfaction_score distinct values: {sorted(df['satisfaction_score'].unique().tolist())}")


if __name__ == "__main__":
    main()
